title : Javeria's Portfolio
description : Hi! I am Javeria, a data analyst and aspiring data scientist with a strong foundation in business. 

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
