title : Javeria's Portfolio
description : My projects are displayed here

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
